pipeline {
    agent any

    environment {
        SMTP_PASSWORD = credentials('SMTP_PASSWORD')
    }

    triggers {
        cron('00 18 * * *') 
    }

    parameters {
        string(name: 'FROM_EMAIL', description: 'Sender email address')
        string(name: 'TO_EMAIL', description: 'Recipient email address')
        string(name: 'HOSTNAMES', description: 'Comma-separated list of hostnames')
    }
    
    stages {
        stage('Clone Repo') {
            steps {
                dir("ssl_expiry") {
                    checkout([
                        $class: 'GitSCM',
                        branches: [[name: 'main']],
                        userRemoteConfigs: [[
                            url: 'https://github.com/Nitesh8011/Jenkinsfile.git'
                        ]]
                    ])
                }
            }
        }
        // stage('Install Dependencies') {
        //     steps {
        //         dir("ssl_expiry") {
        //             sh 'pip3 install -r requirements.txt'
        //         }
        //     }
        // }
        stage('Run Script') {
            steps {
                dir("ssl_expiry") {
                    sh 'python3 main.py'
                }
            }
        }
    }
}
